build: check for backtrace(3) via FindBacktrace
intel/media-driver pull request #1536
Opened 2022-11-01 16:13 UTC by dvrogozh

Fixes: #1533

Change-Id: I81bcdb5e65c26f94b174af9b5e6218c14601c50f
Signed-off-by: Dmitry Rogozhkin <dmitry.v.rogozhkin@intel.com>

2022-11-01 16:38 UTC, bkuhls commented
Building with a musl toolchain and libexecinfo works:

```
-- Looking for backtrace
-- Looking for backtrace - not found
-- Found Backtrace: /home/buildroot/buildroot/output/per-package/intel-mediadriver/host/x86_64-buildroot-linux-musl/sysroot/usr/lib/libexecinfo.so  
```

```
$ readelf -a output/per-package/intel-mediadriver/target/usr/lib/va/iHD_drv_video.so  | grep NEEDED
 0x0000000000000001 (NEEDED)             Shared library: [libexecinfo.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libigdgmm.so.12]
 0x0000000000000001 (NEEDED)             Shared library: [libstdc++.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libgcc_s.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libc.so]
```

2022-11-01 16:49 UTC, bkuhls commented
Building with a glibc toolchain still works:
```
-- Looking for backtrace
-- Looking for backtrace - found
-- backtrace facility detected in default set of libraries
-- Found Backtrace: /home/buildroot/buildroot/output/per-package/intel-mediadriver/host/x86_64-buildroot-linux-gnu/sysroot/usr/include  
```
```
$ readelf -a output/per-package/intel-mediadriver/target/usr/lib/va/iHD_drv_video.so  | grep NEEDED
 0x0000000000000001 (NEEDED)             Shared library: [libigdgmm.so.12]
 0x0000000000000001 (NEEDED)             Shared library: [libstdc++.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libm.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libgcc_s.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]
```

2022-11-02 11:27 UTC, XinfengZhang approved these changes

2022-11-02 11:30 UTC, bkuhls commented
Please do not merge this PR as is because building without libexecinfo on musl/uClibc is still broken due to mos_compat.h not being created, see my pending review.

2022-11-02 15:01 UTC, dvrogozh commented
> building without libexecinfo on musl/uClibc is still broken due to mos_compat.h not being created, see my pending review.

Which comment? Above I see only comments that all works. Did you forget to post?

2022-11-02 15:08 UTC, bkuhls requested changes

2022-11-02 15:09 UTC, bkuhls commented
> Which comment? Above I see only comments that all works. Did you forget to post?

Sorry, while using the Github review feature for the first time I did not notice that the state "Pending" meant that I still had to submit the review so others can see it ;)

2022-11-02 15:34 UTC, dvrogozh commented on media_softlet/linux/common/os/osservice/media_srcs.cmake
> +    configure_file(${CMAKE_CURRENT_LIST_DIR}/mos_compat.h.in ${CMAKE_BINARY_DIR}/mos_compat.h)
Ah, yes. You caught an issue in the PR which I overlooked. Yes, if backtrace is not found at all, then Backtrace_FOUND will be OFF and mos_conmpat.h won't be generated. That's wrong, idea was that this file should always be generated regardless of backtrace found/not-found status. And this file rules out internally whether backtrace was found or not. I'll fix.

2022-11-02 15:38 UTC, dvrogozh commented on media_softlet/linux/common/os/osservice/mos_compat.h.in
> +// in different header files. So, we need to detect which header to be used.
updated comment

2022-11-02 15:39 UTC, dvrogozh commented on media_softlet/linux/common/os/osservice/media_srcs.cmake
> +    configure_file(${CMAKE_CURRENT_LIST_DIR}/mos_compat.h.in ${CMAKE_BINARY_DIR}/mos_compat.h)
Fixed. Can you try again?

2022-11-02 16:02 UTC, bkuhls commented on media_softlet/linux/common/os/osservice/media_srcs.cmake
> +    configure_file(${CMAKE_CURRENT_LIST_DIR}/mos_compat.h.in ${CMAKE_BINARY_DIR}/mos_compat.h)
Building with uClibc (which lacks backtrace(3)) and without libexecinfo works now:
```
$ readelf -a output/per-package/intel-mediadriver/target/usr/lib/va/iHD_drv_video.so  | grep NEEDED
 0x0000000000000001 (NEEDED)             Shared library: [libigdgmm.so.12]
 0x0000000000000001 (NEEDED)             Shared library: [libstdc++.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libgcc_s.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libc.so.0]
```
From my pov this PR can now be merged, thanks!

2022-11-02 16:03 UTC, bkuhls commented on media_softlet/linux/common/os/osservice/mos_compat.h.in
> +// in different header files. So, we need to detect which header to be used.
thanks

2022-11-03 15:16 UTC, dvrogozh commented on media_softlet/linux/common/os/osservice/media_srcs.cmake
> +    configure_file(${CMAKE_CURRENT_LIST_DIR}/mos_compat.h.in ${CMAKE_BINARY_DIR}/mos_compat.h)
Thank you for trying out. We will proceed with the merging this in.

2022-11-03 16:30 UTC, bkuhls approved these changes

2022-11-03 16:44 UTC, bkuhls commented
Build error on "ci / gcc-10-gen12-off" is unrelated
```
2022-11-02T16:27:07.2595421Z /home/runner/work/media-driver/media-driver/media/media_softlet/agnostic/Xe_M_plus/Xe_LPM_plus_base/shared/mediacopy/media_render_copy_xe_lpm_plus_base.cpp:45:10: fatal error: igvpkrn_xe_hpg.h: No such file or directory
```

2022-11-07 15:36 UTC, dvrogozh commented
Rebased to avoid a conflict with some recently merged change.

2022-11-16 16:04 UTC, merged