[VP9] [Encode] Fill padding with gmm CpuBlt on MTL
intel/media-driver pull request #1722
Opened 2023-09-08 07:32 UTC by zlma7001

Fill the padding for unaligned height input with gmmlib CpuBlt() for VP9 encoding on MTL.

2023-09-11 02:08 UTC, leyu-yao approved these changes
LGTM

2023-09-11 06:03 UTC, XinfengZhang approved these changes

2023-09-11 08:54 UTC, leyu-yao requested changes
Cannot merge this now.
I found 270p P010 has crash issue...

2023-09-12 04:43 UTC, leyu-yao approved these changes

2023-09-15 04:44 UTC, merged